- vars:
    config_file: /etc/ssh/sshd_config
    pkgs:
      - zsh
      - autojump
      - sudo
      - mercurial
    config_files:
      - zsh_aliases
      - zsh_functions
      - zshrc
  tasks:
    - name: Configure SSH
      lineinfile: dest="{{config_file}}" regexp="^PermitRootLogin.*yes" line="PermitRootLogin no"
    - name: Install pkgs
      apt: name={{item}} state=latest
      with_items: {{pkgs}}
    - name: Create Michel
      user: name=michel comment="Michel Barret" shell="/usr/bin/zsh"
    - name: Modify root
      user: name=root shell="/usr/bin/zsh"
    - name: Get conf
      hg: repo=ssh://hg@bitbucket.org/barmic/config dest=/opt/config
    - name: Setting conf for root
      file: src="/opt/config/zsh/{{item}}" dest="/root/.{{item}}" state=link
      with_items: "{{config_files}}"
    - name: Setting conf for michel
      file: src="/opt/config/zsh/{{item}}" dest="/home/michel/.{{item}}" state=link
      with_items: "{{config_files}}"
    - name: SSH key for michel
      copy: src="files/sshpubkey" dest="/home/michel/.authorized_keys" mode=0600
