---
- name: Configure SSH (no root)
  lineinfile: dest="{{config_file}}" regexp="^PermitRootLogin.*no" line="PermitRootLogin no"
- name: Configure SSH (no password)
  lineinfile: dest="{{config_file}}" regexp="^PasswordAuthentication " line="PasswordAuthentication yes"
- name: Install pkgs
  apt: name={{item}} state=latest
  with_items: "{{pkgs}}"
- name: Configure SSLH
  template: src=templates/sslh.j2 dest=/etc/default/sslh
  register: config_sslh
- name: Restart SSLH
  service: name=sslh state=restart
  when: config_sslh.changed
- name: Create Michel
  user: name=michel comment="Michel Barret" shell="/usr/bin/zsh"
- name: Modify root
  user: name=root shell="/usr/bin/zsh"
- name: Get conf
  hg: repo=https://barmic@bitbucket.org/barmic/config dest=/opt/config
- name: Setting conf for root
  file: src="/opt/config/zsh/{{item}}" dest="/root/.{{item}}" state=link
  with_items: "{{config_files}}"
- name: Setting conf for michel
  file: src="/opt/config/zsh/{{item}}" dest="/home/michel/.{{item}}" state=link
  with_items: "{{config_files}}"
- name: Create SSH config for michel
  file: path="/home/michel/.ssh/" mode=0700 state=directory
- name: SSH key for michel
  copy: src="files/sshpubkey" dest="/home/michel/.ssh/authorized_keys" mode=0600
