---
- name: Install pkgs
  apt: name={{item}} update_cache=yes state=latest
  with_items:
    - git
    - mariadb-server
- name: Get TinyTiny RSS
  git: repo=https://tt-rss.org/git/tt-rss.git dest=/opt/ttrss
- name: Send SQL
  template: src=templates/create_db_and_user.sql.j2 dest=/root/create_db_and_user.sql
- name: Create TTRSS database and user
  shell: mysql -u root < /root/create_db_and_user.sql
